name: plankton-app
envs:
  - key: DO_API_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: dop_v1_888b2c805a24ff2839758f843194e2569fa2dca9e13078889d3bc615776cae28
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${OPENAI_API_KEY}

services:
  - name: autosportsgpt
    github:
      repo: alextrx818/autosportsgpt
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "8000"
