name: plankton-app
envs:
  - key: DO_API_TOKEN
    scope: RUN_TIME
    type: SECRET
    value: ${DO_API_TOKEN}
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
    value: ${OPENAI_API_KEY}
  - key: WORKSPACE_PATH
    scope: RUN_TIME
    value: /workspace/autogpt
  - key: EXECUTE_LOCAL_COMMANDS
    scope: RUN_TIME
    value: "False"
  - key: ENVIRONMENT
    scope: RUN_TIME
    value: "production"
  - key: PORT
    scope: RUN_TIME
    value: "8000"

services:
  - name: web
    github:
      repo: alextrx818/autosportsgpt
      branch: main
    dockerfile_path: Dockerfile
    instance_size_slug: basic-xxs
    instance_count: 1
    volumes:
      - name: autogpt-data
        mount_path: /workspace/autogpt
        size_gb: 1
