name: plankton-app
services:
  - name: autosportsgpt
    github:
      repo: alextrx818/autosportsgpt
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "8000"
