name: plankton-app
services:
  - name: web
    github:
      repo: alextrx818/autosportsgpt
      branch: main
    envs:
      - key: DO_API_TOKEN
        scope: RUN_TIME
        type: SECRET
        value: ${DO_API_TOKEN}
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${OPENAI_API_KEY}
      - key: WORKSPACE_PATH
        scope: RUN_TIME
        value: /workspace
      - key: EXECUTE_LOCAL_COMMANDS
        scope: RUN_TIME
        value: "False"  # Prevent any local execution
    build_command: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    run_command: python sports_web.py
    instance_size_slug: basic-xxs
    instance_count: 1
    filesystem:
      - name: autogpt-data
        mount_path: /workspace
        size_gb: 1
