name: autosportsgpt
services:
- name: api
  github:
    branch: main
    deploy_on_push: true
    repo: yourusername/autosportsgpt
  build_command: pip install -r requirements.txt
  run_command: uvicorn api_server:app --host 0.0.0.0 --port 8080
  envs:
  - key: SPORTS_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: SPORTS_API_HOST
    scope: RUN_TIME
    type: SECRET
  instance_size_slug: basic-xxs
  instance_count: 1
